### ISSUE TITLE
Error: Cannot find module '@mischnic/json-sourcemap' Need Help to fix the error

### ISSUE THREAD

**Issue by Ammarkhan227** [Ammarkhan227/Food-Delivery#2]
🚨 Build failed.

Error: Got unexpected null

  Error: Got unexpected null
      at nullthrows (D:\Food-Delivery\node_modules\nullthrows\nullthrows.js:7:15) at PackagerRunner.loadConfig (D:\Food-Delivery\node_modules\@parcel\core\lib\PackagerRunner.js:150:42) 
      at PackagerRunner.loadConfigs (D:\Food-Delivery\node_modules\@parcel\core\lib\PackagerRunner.js:140:16)
      at PackagerRunner.run (D:\Food-Delivery\node_modules\@parcel\core\lib\PackagerRunner.js:126:20)        
      at Object.runPackage (D:\Food-Delivery\node_modules\@parcel\core\lib\worker.js:153:17)
      at async Child.handleRequest (D:\Food-Delivery\node_modules\@parcel\workers\lib\child.js:203:9)

**Comment by Ammarkhan227** [comment]
Hi can anyone help me with this issue 🥲🥲🥲 ????
